application: andrewproxy
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /fonts
  static_dir: fonts 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: app.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
